# Generated by Django 4.2.7 on 2023-11-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_product_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
