# Generated by Django 4.2.7 on 2023-11-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
