# Generated by Django 4.2.7 on 2023-11-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_product_digital_product_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Numberofpages',
            new_name='numberofpages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Publishingyear',
            new_name='publishingyear',
        ),
    ]
