# Generated by Django 4.2.7 on 2023-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rename_author_product_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numberofpages',
            field=models.IntegerField(),
        ),
    ]
