# Generated by Django 4.2.7 on 2023-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_product_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
