# Generated by Django 4.2.7 on 2023-12-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_product_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
